// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGjWyPPECLs1ROVqoPmDjjzukgzmEWqS8',
    appId: '1:128585481330:ios:b5b010748614ca0e6b96eb',
    messagingSenderId: '128585481330',
    projectId: 'smarthealth-app-souhail',
    storageBucket: 'smarthealth-app-souhail.firebasestorage.app',
    iosBundleId: 'com.example.smarthealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUSD5dyObHISn-5Zlr3OS5D5XZpeHpD5U',
    appId: '1:128585481330:web:9e27a7fba06389736b96eb',
    messagingSenderId: '128585481330',
    projectId: 'smarthealth-app-souhail',
    authDomain: 'smarthealth-app-souhail.firebaseapp.com',
    storageBucket: 'smarthealth-app-souhail.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUSD5dyObHISn-5Zlr3OS5D5XZpeHpD5U',
    appId: '1:128585481330:web:736f191483f8b58e6b96eb',
    messagingSenderId: '128585481330',
    projectId: 'smarthealth-app-souhail',
    authDomain: 'smarthealth-app-souhail.firebaseapp.com',
    storageBucket: 'smarthealth-app-souhail.firebasestorage.app',
  );

}